// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD2NfLJarJpWteXtba0UKuwv_veOC1giI',
    appId: '1:39894664505:web:9523326cf1326eb546d4e8',
    messagingSenderId: '39894664505',
    projectId: 'the-game-e7c4c',
    authDomain: 'the-game-e7c4c.firebaseapp.com',
    databaseURL: 'https://the-game-e7c4c-default-rtdb.firebaseio.com',
    storageBucket: 'the-game-e7c4c.appspot.com',
    measurementId: 'G-WF38326DYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByV_Z85HWxvPXV7zsu-u-nS9Q4WsSeo_g',
    appId: '1:39894664505:android:93c7ebcc6af52bfe46d4e8',
    messagingSenderId: '39894664505',
    projectId: 'the-game-e7c4c',
    databaseURL: 'https://the-game-e7c4c-default-rtdb.firebaseio.com',
    storageBucket: 'the-game-e7c4c.appspot.com',
  );
}
